### ISSUE TITLE
Use .npmrc auth token

### ISSUE THREAD

**Issue by ocombe** [ClearTax/post-merge-install#7]
Hello, it does run `npm install` on git pull, but I have a package in a private registry, and we're using `.npmrc` to define the auth token used to connect to that registry:

```
@custom_private_pkg:registry=https://npm.custom_private_pkg.com/
//npm.custom_private_pkg.com/:_authToken=SOME_PRIVATE_TOKEN
```

Because of this, we're getting a 404 not found for this package, because it doesn't use the auth token for this registry, and doesn't use the private registry.

**Comment by rheaditi** [comment]
Hey @ocombe!

In `post-merge-install` we simply run the `npm install` [as a command](https://github.com/ClearTax/post-merge-install/blob/6e5af7793f82d283c2c5ff97cfb88c6b30d6daae/post-merge.js#L51-L54) with the current working directory of the command set to the directory where the changed package/lockfile was found..

I just tested this out locally:
When using a private / scoped registry, the project `.npmrc` config file seems like it needs to be in the _same directory_ as the `package[-lock].json` file in order for the config to apply. This behaviour seems to be the same for simple `npm install` and even when adding new dependencies with `--save` or `--save-dev`.

Please try these and see if it works for you:-

- Have the `.npmrc` in the same directory as where the `package.json/package-lock.json` file is.
- Try setting the registry & auth token as `userconfig` eg:-

```sh
npm config set @custom_private_pkg:registry https://npm.custom_private_pkg.com/
npm config set '//npm.custom_private_pkg.com/:_authToken' SOME_PRIVATE_TOKEN
```

Hope this helps! 😄 

---

If the issue still persists, please provide some more information about where the `.npmrc` file is with respect to the package files; possibly share the redacted output after running `npm config list` command and the general directory structure of your project.

**Comment by maddhruv** [comment]
Hey @ocombe did you get a chance to check the above suggestion?
I am closing this, for now, feel free to re-open 😄
